services:
  web-thinkless:
    image: node:20
    container_name: thinkless-web
    working_dir: /app
    ports:
      - "81:3000"
    volumes:
      - .:/app
    environment:
      DB_HOST: db-thinkless
      DB_PORT: 3306
    depends_on:
      - db-thinkless
    command: sh -c "npm install && node server.js"

  db-thinkless:
    image: mysql:8.0
    container_name: thinkless-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - thinkless_db_data:/var/lib/mysql # ← persistance
      - ./database/thinkless_db.sql:/docker-entrypoint-initdb.d/init.sql # ← auto-import
    ports:
      - "3307:3306"

volumes:
  thinkless_db_data: # ← volume nommé
