services:
  web-thinkless:
    image: node:20
    container_name: thinkless-web
    working_dir: /app
    ports:
      - "81:3000"
    volumes:
      - .:/app
    networks:
      - f1_network
    depends_on:
      - db-thinkless
    command: sh -c "npm install && node server.js"

  db-thinkless:
    image: mysql:8.0
    container_name: thinkless-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: thinkless_db
    volumes:
      - thinkless_db_data:/var/lib/mysql # ← persistance
      - ./thinkless_schema.sql:/docker-entrypoint-initdb.d/init.sql # ← auto-import
    networks:
      - f1_network

volumes:
  thinkless_db_data: # ← volume nommé

networks:
  f1_network:
    external: true
